# from rasa base image
FROM rasa/rasa:3.1.0
# copy all source and the Rasa generated model
COPY ./faq/ /app

# inform which port will run on
EXPOSE 5006

USER root

ENTRYPOINT []
ENV shell_mode false

RUN rasa train

# # launch script (rasa shell or rasa run)
# CMD sh -c 'if [ "$shell_mode" = false ]; then rasa run -p 5006 --cors "*"; else rasa shell -p 5006; fi'


CMD sh -c 'if [ "$shell_mode" = false ]; then rasa run --enable-api --log-file rasa.log --debug -p 5006 --cors "*" && rasa run actions; else rasa shell -p 5006; fi'